const recipe = [
    {name: "Borsht",
    description: "Borscht is the quintessential Ukrainian dish - it’s eaten during the holidays, as a weekday meal, or even for occasions such as funeral wakes.Adored by both vegetarians and meat-eaters alike, Borscht is a hot beetroot soup that is usually red in color.",
    image: "/borsht.jpeg",
    ingredients: ["12 cups beef or vegetable broth or stock low sodium", "5 cups green or red cabbage thinly sliced", "1 large onion chopped", "3 medium carrots chopped", "2 tbsp olive oil", "3 large beets peeled and cut into matchsticks", "4 large potatoes peeled and cubed", "6 oz can tomato paste low sodium", "2 tsp salt", "3 bay leaves", "Pinch of sugar", "3 large garlic cloves grated", "Ground black pepper to taste", "1/4 cup dill or parsley finely chopped","Sour cream and rye bread, for serving"],
    directions: ["Step 1","In a large pot (I use 6 quart Dutch oven) add broth bay leaves and bring to a boil", "In the meanwhile, wash, peel and cut vegetables.",  "Step - 2","Once broth is boiling, add cabbage, cover and bring to a boil. Then reduce heat to low and cook for 20 minutes.", "Step - 3", "In the meanwhile, preheat large skillet on medium heat and swirl 1 tbsp of oil to coat. Add onion, carrots and saute for 5 minutes, stirring occasionally.", "Step - 4", "Add beets, remaining 1 tbsp of oil and cook for another 3-4 minutes.", "Step - 5", "Transfer sauteed veggies to a pot along with potatoes, tomato paste and salt. Cover, bring to a boil and cook on low heat for 20 minutes.", "Step - 6", "Turn off heat. Add sugar, garlic and pepper. Stir and let borscht sit for 10 minutes to allow flavours to marry each other. Add dill, stir and adjust any seasonings to taste.", "Step - 7", "Serve hot with a dollop of  sour cream, bread and garlic clove on the side."],
    category:"Soups",
},
    {name: "Chicken Kiev",
    description: "Chicken Kiev is the dish that has brought fame to Ukraine. The simple combination of fresh chicken filet with a piece of butter is considered to be quite exquisite all over the world. To ensure that butter does not flow during the frying, you’ll need a lot of practice and true professionalism.",
    image: "/chickenKiev.jpeg",
    ingredients: ["4 Chicken Breasts", "2 eggs beaten", "¾ cup flour", "1 ½ cups fine dry white bread crumbs", "Salt and Pepper to taste", "Extra light olive oil or Canola oil to sauté", "Kiev Butter:", "8 Tbsp unsalted butter at room temperature", "1 garlic clove minced", "1 tbs lemon juice", "1 Tbsp chopped fresh parsley", "1/2 tsp salt", "1/2 tsp pepper"],
    directions: ["Step 1 - Kiev Butter",  "In a medium bowl, mash or cream together 8 tablespoons of softened butter with 1 garlic clove minced, 1 tbs lemon juice, 2 Tbsp finely chopped fresh parsley, 1/2 tsp salt and 1/2 tsp pepper.", "Shape into a log ¾” thick, cover with plastic wrap and place in freezer while working on everything else.", "Step -2",  "Pat dry the chicken. Remove the tenderloins from the chicken breasts (if any) and carefully pound them to 1/8” thick and not thinner or it may tare easily. It should be thinner on the edges which will help to seal the chicken and prevent butter from oozing out when cooking.", "Peel off the wax paper.", "Step - 3", "Sprinkle one side of the chicken with salt and pepper.", "Remove prepared butter from the freezer and cut into 4 equal pieces. Place one piece of butter in the center of the chicken breast.Fold two sides down over the butter. Fold in the other end of the chicken breast and roll up the rest of the way. If you have gaps in your chicken, use the thinly pounded tenderloin to fill them before rolling.(Roll all 4 of the chicken breasts the same way).", "Step - 4",  "Heat 1” canola oil in a deep pot over medium heat until a piece of bread turns golden in 1 minute (about 325-350 degrees F). Initial heating should be to about 350 since the temp drops after you put each chicken in. You should have enough oil to cover the chicken at least half-way (1 1/2 to 2 inches).", "Step - 5",  "Set up 3 separate dishes. (1) flour (2) beaten eggs (3) bread crumbs.Gently cover the finished chicken in flour, dusting off the excess flour. Next, dip the chicken in the egg and finally cover chicken with bread crumbs (gently shake off excess).Gently place the chicken in the hot oil and fry until golden brown (4 min each side), then turn over. Wait to add each chicken Kiev to the oil if you place in 2 at once the oil will cool down too quickly.Remove chicken to a baking dish.", "Step - 6",  "Once all 4 pieces are done frying, bake uncovered for 18 to 20 minutes at 350°F. Than drain on paper towels for 10 minutes before serving. Be careful of the first spurt of butter when the chicken is pierced."],
    category:"Main"
},
    {name: "Deruny",
    description: "There are many delicious potato dishes in Ukraine, but the most well-known one has to be these delightful fried potato pancakes",
    image: "/Deruny.png",
    ingredients: ["4 large Yukon potatoes (about 2 lbs)", "1 small yellow onion (4 oz)", "1 large egg", "3 tablespoons all-purpose flour", "1 teaspoon fine salt or to taste", "1/4 teaspoon baking soda", "sunflower oil for frying"],
    directions: ["Step - 1", "Peel 4 large Yukon potatoes and 1 small yellow onion. Line a sieve with a large bowl so that potatoes will drain while you finish grating. Into a sieve, grate potatoes and onion onto the star-shaped hole on grater, taking turns. Onion juice will prevent potatoes from browning. Dispose most of the potato juice from bowl underneath the sieve, but do not wash the potato starch. Keep the potato starch and add the grated potatoes and onions to the bowl with starch.", "Step - 2", "Add 3 tbsp all-purpose flour, 1 egg, 1 tsp fine salt and 1/4 tsp baking soda into the potato mixture. Mix well until incorporated. Potato batter will be thick, but still liquid enough to spoon.", "Step - 3", "Heat 2-3 tbsp of grapeseed oil in a large nonstick skillet over medium heat. Spoon 1 heaping tablespoon of potato mixture to make pancakes, about 1” apart. Fry on each side until golden brown (about 3-4 mins each side). Repeat the same procedure for the remaining batter.", "Serve deruny warm with a dollop of sour cream."],
    category:"Main"
},
    {name: "Holubtsi",
    description: "Almost every nation in this world has its own version of stuffed cabbage rolls.Holubtsi is one of the most well-known Ukrainian dinner recipes. So if you are looking for a healthy and light dinner option, learn how to roll some Holubtsi. Similar to Deruny, these delicious rolls pair amazingly well with sour cream",
    image: "/Holubtsy.png",
    ingredients: ["1 large green cabbage", "2 1/2 pounds ground beef", "2 cups cooked rice", "2 large eggs", "1 medium onion rough chopped", "1 medium green bell pepper cut into strips",  "10 cherry tomatoes quartered", "1 tablespoon salt", "2 10 3/4 ounce cans condensed tomato soup", "1 1 pound canned tomatoes", "1 bottle chili sauce", "1 tablespoon basil dried", "4 bay leaves dried"],
    directions: ["Step - 1", "Wash, core, and boil cabbage in a deep pot. Once the water comes to a boil, turn the heat to low and simmer the cabbage until the outer leaves can easily be pulled away from the cabbage. The leaves' color will change to a brighter green. As you pull the leaves off, allow them to cook in the hot water for a little longer if necessary, until they're pliable.", "Step -2", "In a large bowl, mix ground pork, carrots, onion, parsley, garlic, egg, oil, tomato paste, salt, black pepper, and paprika. Add washed and strained rice and mix to combine.Once the cabbage leaves have cooled, slice off the large spine going down the middle of the leaves, and use the spines to layer the bottom of a large, heavy-bottomed pot. This layer of leaves will keep the stuffed cabbage from sticking to the pot or burning.", "Step - 3", "Fill the trimmed cabbage leaves with 1 tablespoon of filling mixture and roll the leaves tightly over the filling. Depending on the size of the leaf, they may require more or less filling. Place the stuffed cabbage seam-side down into the lined pot continue until you have one layer, then start another layer. Depending on the size of the pot, you may end up with two or three layers of cabbage rolls.", "Step - 4", "Preheat Oven to 325 Degrees F.", "Step - 5", "Add water and tomato paste to a small saucepan and season with salt and sugar. Add oil and whisk over medium heat until the tomato paste is dissolved and the sauce comes to a boil.Pour sauce over stuffed cabbage, cover the pot, and bake the stuffed cabbage for one hour or until the rice is tender.", "Serve stuffed cabbage with sour cream"],
    category:"Main"
},
    {name: "Kutia",
    description: "When it comes to well-known holiday delicacies from Ukraine, you can’t ignore Kutia. This sweet grain pudding is usually served as part of a 12-course Christmas Eve dinner, despite being created before Christianity.",
    image: "/Kutia.png",
    ingredients: ["1 1/2 cups wheat berries", "4 1/2 cups of milk or water", "3/4 cups poppy seed", "1/2 cup honey", "1/2 cup raisins", "2/3 cup dry apricots chopped", "2/3 cup slivered almonds or chopped walnuts", "1/8 tsp salt"],
    directions: ["Step - 1", "Rinse wheat berries in cold water until water runs clear, then transfer to a bowl and soak overnight in lukewarm water, adding enough water to cover 2-inches above the wheat berries.", "Step - 2", "The following day, drain wheat berries, place them in a medium-sized heavy pot, cover with 4 1/2 cups of milk and bring everything to a boil over high heat. When milk starts to boil, reduce heat to low, cover with lid and simmer until wheat berries are very tender, 3 1/2 - 4 hours, depending on the quality of the wheat, stirring occasionally to prevent sticking. Add more milk if needed to keep the wheat berries fully submerged (If you simmer over low heat, you won't have to add anymore milk).", "Step - 3",  "While the wheat berries are on the stove, rinse 3/4 cups of poppy seeds thoroughly in a fine mesh sieve, drain well, and transfer to a medium sauce pan and add 3 cups water. Over medium heat, bring to a simmer (Don’t boil). Turn off. Cover with lid and let it sit for 30 min. Return to a simmer (don’t boil). Turn off. Cover and let it sit for another 30 minutes. Drain poppy seeds well through a colander or by keeping lid on and placing several layers of cheese cloth over lid to catch stray poppy seeds. Push the poppy seeds through a food grinder, using the fine grinding plate (You can also mill the poppy seeds in batches in a clean coffee grinder).", "Step - 4", "Preheat the oven to 350˚F. Spread 2/3 cups of slivered almonds on a baking sheet and toast them for 5 minutes. Set them aside and reduce temperature to 325˚F.", "Step - 5", "When wheat berries get very tender, drain off the milk in a glass measuring cup. Keep 1/2 cup of the cooked milk and discard the rest. Combine 1/2 cup of honey with 1/2 cup of saved milk and stir until combined.", "Step - 6",  "Place cooked wheat berries in a mixing bowl, add ground poppy seeds, 1/2 cup raisins, 2/3 cup dry chopped apricots, 2/3 cup toasted slivered almonds, honey-milk mixture and 1/8 tsp salt. Mix everything together and place in an casserole or pie dish, than bake your kutia for 20 min uncovered at 325˚F.", "Step - 7", "Remove kutia from the oven, cover with foil and let it rest 15 min. Serve warm or cold. The longer it sits, the more flavor it will have. Kutia will last in the fridge for a good 2 weeks."],
    category:"Desserts"
},
    {name: "Varenyky",
    description: "These soft, cheesy dumplings will satisfy your craving.Varenyky is the Ukrainian spin of the worldwide famous European dish Pierogies, and it plays a vital role in Ukrainian culture.",
    image: "/varenyky1.jpeg",
    ingredients: ["For Dough:", "5 cups all-purpose flour", "1 teaspoon salt", "2 tablespoons butter softened", "1 cup milk", "½ cup water", "For Filling:", "6 medium potatoes cut into small cubes", "2 large onions finely chopped", "½ cup butter", "1 cup shredded Cheddar cheese", "salt and pepper to taste "],
    directions: ["Step - 1", "To make the dough, combine the flour and salt in a large bowl. Make a well in the center and add the soft butter and evaporated milk stir gently until all the liquid is absorbed. Add water only as needed, kneading continuously until dough sticks together. Place dough into a greased bowl, turn to coat, and let rest for 30 minutes.", "Step - 2", "To make the potato filling, place potatoes into a saucepan with water to cover. Bring to a boil and cook until tender, about 10 minutes. Drain and set aside. Melt 1/2 cup butter in a medium skillet, over medium heat. Saute onions in butter until tender. Mix the onions into the potatoes along with the cheese and season with salt and pepper to taste.",  "Step - 3", "To make the sauerkraut and cabbage filling, pour the drained sauerkraut into a large saucepan. In a medium skillet, saute 2 onions in 1/2 cup butter until tender, about 5 minutes. Stir the onions into the sauerkraut along with the cabbage and chicken bouillon cube. Cook over low heat until liquid evaporates. Season with pepper and remove from heat. Allow the mixture to cool, then run through a grinder or food processor.", "Step - 4", "Remove the dough from the bowl onto a lightly floured surface. Roll out to 1/8 inch in thickness. Cut into 3 inch circles. Place one tablespoon of filling onto one side of the circle. Fold the other half over and press the edges to seal. Place finished dumplings onto a floured tray and keep covered.", "Step - 5", "Bring a large pot of water to a boil. Drop 10 or so dumplings into the water at a time. Cook for 3 to 5 minutes, then remove to a colander to drain. Place finished dumplings onto a lightly oiled dish and turn them to coat with a thin layer. This will keep them from sticking together.", "Serve dumplings with fried onions and sour cream. Cooled dumplings also can be fried in oil and butter for a nice crispy surface."],
    category:"Main"
},
    {name: "Salo",
    description: "Salo is one of the most popular Slavic dishes you’ll ever find. The traditional salo recipe is popular in most Slavic countries but it originates from Ukraine and it’s a very important part of the local culture.",
    image: "/Salo.jpeg",
    ingredients: ["2.5 Lb pork belly/pork fat", "1 and 1/2 Cups salt (for the base)", "6 Teaspoons salt (for salt rubs)", "1 Teaspoon paprika","½ Teaspoon coriander", "1 teaspoon black pepper", "2 Bay leaves", "3 Garlic cloves sliced"],
    directions: ["Step - 1", "Put the pork on a cutting board and let it adjust to the room temperature for 20 minutes.","Step - 2", "Pour the salt (for curing) in a glass container.", "Step - 3", "Break the bay leaves into tiny pieces.", "Step - 4", "Mix the pieces with coriander, black pepper, and 1 tablespoon of salt and grind using mortar and pestle.", "Step - 5", "Add the paprika and the rest of the salt (for the base) and mix everything well.", "Step - 6", "Slice the garlic and mix it with the thyme and 1 teaspoon of salt.", "Step - 7", "Grind the garlic mix.", "Step - 8", "Cut the pork into four blocks and add them into the glass container with the salt. 8.1 During the whole process, you’ll have to replace the salt (it will get wet) with a dry one.", "Step - 9", "Blacken the pigskin using a torch and use some hot water to scrape the charred part. You may have to repeat this process 2-3 times.", "Step - 10", "Roll every piece of pork belly in the salt and place the pigskin down when placing it into the containers.", "Step - 11",  "Cover the containers and let the pork cure for two days in a room with a temperature of 65F or four days in a room with around 40F.", "Step - 12", "In a couple of days, wash the salt rub under cold water and dry the salo with paper towels.", "Step - 13", "Place the salo into new, dry containers covered with paper towels and let it mature for 10-14 days.", "Step - 14",  "Take out the salo, serve it, and enjoy."],
    category:""
    },
    {name: "Holodets/ Kholodets",
    description: "Kholodets or Meat Aspic is a traditional Ukrainian dish that is served with spicy horseradish and beet sauce. Although, yes, the term “meat jelly” may not be that enticing, you would change your mind after just one bite! The dishs name comes from the Ukrainian word holodnyii, which means “cold”. You can often see this dish at important celebrations like New Year Eve",
    image: "/Holodets.png",
    ingredients: ["2 lb pork legs, soaked in cold water and refrigerated 3 hours to overnight", "5-8 large chicken drumsticks (or any meat with the bone in)", "2 medium onions", "1 large carrot", "1 stick of celery", "2 bay leaves", "5-10 peppercorns", "2 tsp salt + more to taste", "6-8 cloves garlic peeled and minced"],
    directions: ["Step -1", "Make sure you soak the pork legs in cold wate (3 hours to overnight - it's also a good way to thaw the pork)", "Step - 2", "In a large pot, add pork legs, and chicken drum sticks. Add enough water to cover all of the meat. Set over high heat, cover and bring to a boil. As soon as it starts boiling, remove from heat and drain off the water. Rinse the meat, refill with fresh water (enough water to cover all of the meat, plus an extra 1/2-inch over the meat); Don't add too much water or it won't be gelatiney enough later. Cover and bring to a boil again. Reduce heat to a light boil/simmer and set a timer for 5 hours", "Step - 3", "After cooking for 5 hours, Add 1 large carrot, 2 medium onions (both ends removed), 1 celery stick, 2 bay leaves, 5-8 peppercorns and 2 tsp salt into the pot and continue boiling on low heat 1 more hour. It should look like a nice chicken broth. Now it's important that you do not discard the broth and do not add more water to the pot!", "Step - 4", "Remove the drumsticks and carrot from the broth and let them cool. Discard pork legs, onion and bay leaves. Use a fine mesh sieve with 3 bounty paper towels over the sieve and filter the broth through the paper towels. You will be left with a clean broth.", "Step - 5", "Peel and press 4 garlic cloves into the broth and do a taste test to see if more salt is needed.", "Step - 6", "Once the meat has cooled, use a fork to separate meat from the bones. Keep the good meat; discard the bones. Thinly slice the carrot. You can make one big holodets in a rectangular pyrex dish or you can make smaller serving bowls.", "Step - 7", "Start by placing carrots on the bottom and top with some dill if you wish. Next add the meat in an even layer and pour broth over the meat; enough to cover the meat and a little extra over the top. Refrigerate 3 hours to overnight, or until firm. Serve with red horseradish/hren mustard. Once it's set, set the bowl in hot water for a few seconds, then use a slim spatula to release the gelatin from the dish. Or you can just serve it out of the dish and save yourself a step."],
    category:"Main"
    },
    {
    name: "Pampushky ",
    image: "/pampushky.jpeg",
    description: "Pampushky is the epitome of garlic bread! With a soft pillowy texture and flavorful garlic toppings, Ukrainian garlic bread will surely make your mouth water.",
    ingredients: ["2 1/4 teaspoons (7 grams) active dry yeast", "1 teaspoon granulated sugar", "1 cup (225 milliliters) lukewarm water 105-115˚F (40-46˚C)", "2 1/2 cups (325 grams) white bread flour plus more for dusting divided", "1 1/2 teaspoons (8 grams) fine sea salt", "Topping:", "3 tablespoons (45 milliliters) sunflower oil plus more for greasing the pan", "4 cloves garlic peeled and minced", "2 tablespoons finely chopped fresh parsley", "Pinch salt", "1 large egg beaten"],
    directions:["Step - 1", "In the bowl of a stand mixer or a large bowl, sprinkle the yeast over the warm water along with the sugar. Stir to combine and allow to rest until frothy, 5-10 minutes. Mix in 1 1/4 cups (163 grams) of the bread flour, cover with plastic, and allow to rest in the refrigerator overnight.", "Step - 2", "Mix in the remaining 1 1/4 cups (163 grams) flour and the salt.", "Step - 3", "On a floured work surface, knead the dough until smooth and elastic.", "Step - 4", "Grease a round 9 inch (23 centimeter) ovenproof dish with oil.Divide the dough into 8 equal pieces.", "Step - 4",  "Form each piece into a ball and arrange in the oiled dish. Cover and allow to rest at room temperature until doubled and the rolls are touching.", "Step - 5", "Preheat oven to 425˚F (220˚C).", "Step - 6", "In a small bowl, combine the 3 tablespoons oil, garlic, parsley, and salt. Set aside. ", "Step - 7", "Once the pampushky have risen, brush with the beaten egg and bake until golden, 20-25 minutes. Immediately brush with the garlic oil and serve warm."],
    category:""
    },
    {
    name: "Banush",
    image: "/Banush.png",
    description: "Originating in the Carpathian mountains, Banush was once linked with the Hutsul minority, with males being assigned to make the meal.This traditional Hutsul dish is made using maize flour and sour cream. Sometimes, it is elevated with toppings like fried bacon pieces, crispy cracklings, mushroom sauce, and crumbled Bryndza",
    ingredients: ["1/4lb pork fatbackchopped", "2 cups water", "1 cup 2% milk (lactose free if needed)", "1/2 teaspoon salt", "1 cup cornmeal / polenta", "1/4 cup light feta cheese crumbled (or sheep's milk cheese)", "fresh parsley chopped (optional)"],
    directions:["Step - 1", "In a sauté pan over medium-high heat, add the chopped pork and cook, stirring often, until the pieces are well browned and thoroughly cooked.", "Step - 2", "Remove from heat, and using a slotted spoon, transfer the pork to a paper towel-lined plate. Set aside. ", "Step - 3", "In a medium saucepan over medium-high heat, add the water, milk, and salt. Bring to a simmer then stir in the cornmeal. Reduce the heat to medium and keep stirring as it cooks (about 6 or 7 minutes) until the liquid is absorbed and it thickens.", "Serve topped with pork and crumbled feta cheese. Optionally, garnish with some fresh chopped parsley and serve with a side of sour cream."],
    category:"Main"
    },
    {
    name: "Belyashi",
    image: "/Belyashi.png",
    description: "If you are looking for a simple yet filling Ukrainian lunch recipe, go for some Pirozhki! These yeast-leavened boat-shaped buns are the ultimate comfort food in this country, especially when served a hot bowl of soup.",
    ingredients: ["Ingredients for the Meat Piroshki Dough:", "1 1/2 Tbsp oil", "15 oz warm water", "4 cups + 2 Tbsp all-purpose flour (divided)", "1 tsp salt", "1 Tbsp Active Dry Yeast","Ingredients for the Meat Filling:", "1 lb ground turkey",
    "1 lb ground beef (Fat content: 80/20)", "2 Tbsp olive oil","1/2 tsp salt","1/4 tsp pepper", "1/2 tsp garlic powder", "1/2 large onion, finely diced", "1 medium carrot, finely grated", "3 Tbsp dill", "2 Tbsp mayonnaise", "1/2 cup warm water"],
    directions:["How to Make Meat filling for Belyashi:", "Step -1", "Heat a large skillet over medium/high heat. Brown ground beef and turkey, breaking it up into small pieces with a spatula. Season meat with 1/2 tsp salt, 1/ tsp pepper and 1/2 tsp garlic powder.", "Step - 2", "When the meat is almost done, add diced onion and saute 5 minutes, stirring occasionally.", "Step - 3", "Add shredded carrots and saute another 3 minutes, stirring occasionally, Add 3 tbsp dill, mix well,Add mayo, stir well. ", "Step - 3", "Stir in 1/2 cup water to moisten the meat mix. Transfer meat mix to a bowl and let cool to warm or room temperature.", "How to make the Dough:", "Step - 1", "The easiest way to do this is in a bread maker. If you have one, set it to the dough setting and add the ingredients in the following order: Oil, water, 2 cups flour, salt, 2 cups + 2 Tbsp flour, yeast. A bread maker will do the following: mix, let dough rise, mix again and let the dough rise (It takes about 1 to 1 1/2 hours) and once it s done in the bread maker, its ready to go.", "Step - 2", "You can also make this dough using a stand mixer with a dough hook on speed 2(mix all the ingredients together, let rise, mix again and then let it rise in a warm place (like the oven). (It should be 2 to 2 1/2 times in volume). While it's rising, work on the meat filling for piroshki - see below.", "Step - 3", "Put the finished dough onto a well floured cutting board, dust the dough with flour and with well-floured hands, shape it into a large log.It will rise more as you make the piroshki.", "Step - 4", "Cut off pieces one at a time about 3/4″ thick.", "Step - 5", "Place the piece of dough over your well-floured hand (dough will be sticky) and shape it into a 3″ to 4″ circle using your hands. Do not put flour on the side where you are going to put the meat, otherwise the sides won t seal.", "Step - 6", "Stir the meat mix to distribute the juices. Place 1 heaping tablespoon of meat filling in the center.Cover the meat with the sides of the dough (being careful not to let oils or juices seep out), and pinch the edges together to seal the dough. Flatten the pirojki slightly to make them a more uniform size.", "Step - 7", "Heat oil in a large, deep, heavy-bottomed pan or cast iron dutch oven. There should be enough oil to cover the pirojki half-way up the side, Place them in the hot oil and fry until deep golden brown,", "Place on paper towels to cool and enjoy!"],
    category:""
    },
    {
    name: "Nalesniki",
    image: "/Nalysnyky.png",
    description: "Here is another classic breakfast option in Ukraine that is elevated with cheese: Nalesniki! These pancakes can be filled with various ingredients, like canned berries and sweet cottage cheese. You can even top them with sour cream and extra berries.",
    ingredients: ["Crepe:", "4large eggs", "1 cup whole milk", "6 tablespoons cold water", "1 cup all-purpose flour", "1⁄2 teaspoon salt", "CHEESE FILLING:", "2 cups cottage cheese", "2 large egg yolks", "2 tablespoons whipping cream", "1⁄4 teaspoon salt", "1 teaspoon chopped fresh dill weed or 1/2 teaspoon dried dill weed", "1⁄8 cup butter (for frying)", "1⁄4 cup butter, for dotting"],
    directions: ["TO MAKE CREPES.", "Step - 1", "In a bowl, using a hand held electric mixer, beat eggs until light and fluffy.Add milk, water, flour and salt and beat until all ingredients are incorporated and batter is smooth.", "Step - 2", "Heat a 6 inch frying pan on medium heat.Butter the pan lightly and pour about 1/4 cup of batter into the pan, swirling the pan until the batter spreads evenly in the pan.Cook crepes on medium heat for about 1 minute or until lightly browned.Bake on 1 side only, do not turn over.Continue to cook the crepes, buttering the frying pan each time.Place the cooked crepes on a platter and keep warm in the oven at 250°F.", "TO MAKE CHEESE FILLING.", "Step - 1", "Place the cottage cheese in a cheese cloth and squeeze out as much moisture as possible.", "Step - 2", "Transfer the cheese to a mixing bowl.Add egg yolks, cream salt, and dill weed and mix to blend well.", "Step -3","Remove warmed crepes from the oven and increase oven temperature to 350°F.", "Step - 4", "Separate and place 1 crepe with the brown side down on a smooth surface.Spoon about 1 heaping tablespoon of cheese filling near one edge of the crepe.Start rolling the crepe over the filling, tuck in each side to prevent the filling from falling out, and continue to roll.Continue to fill and roll the remaining crepes.", "Step - 5","Place the finished nalysnyky into a lightly buttered 13 inch by 9 inch oven proof casserole dish in layers.Dot each layer with some butter.", "Bake in preheated 350 F oven for 20 minutes.", "Serve hot with melted butter, a dollop of sour cream or yogurt."],
    category:"Desserts"
    },
    {
    name: "Syrniki",
    image: "/syrnyky1.png",
    description: "Syrniki are small, thick Ukrainian sweet cheese pancakes. They might not have a lot of ingredients and look a bit unassuming, but these little bites are soft, fluffy and deliciously good.",
    ingredients: ["8 oz farmer's cheese/quark 225g (tvorog)", "¼ cup all purpose flour 35g plain flour", "2 tablespoon sugar", "1 egg", "¼ teaspoon vanilla extract", "2 tablespoon oil for frying"],
    directions:"Place the cheese, flour, sugar, egg and vanilla for the pancake mixture in a bowl and mix everything together so that the ingredients are well combined but try not to over-mix.Place the additional flour for coating in a small flat bowl or plate. Using either a cookie scoop or a dessert spoon, take a spoonful of the pancake mixture and then lightly round it off in your hands to form a round patty. They are usually on the thick side compared to regular pancakes, but also not just a slightly squished ball.Place the pancake into the flour for coating to coat underneath, carefully turn it over to coat the other side then gently shake off any excess. Set aside on a plate and repeat forming and dredging in flour with the rest of the mixture. You should get between around 7 and 11 pancakes, depending on quite how big you make them.As you are working on forming the pancakes, warm a small skillet/frying pan over a medium heat (non-stick or cast iron is best). Add the oil (and butter, if using) and let it warm.Once the oil is hot, add a few of the pancakes to the skillet. If you're using an 8in (20cm) skillet you probably want to only cook around half at a time so that you don't overcrowd the pan.Cook the pancakes for around 3 - 4 minutes until the underside is gently brown then turn and cook another 2 - 3 minutes on the second side. Remove from the skillet and drain on kitchen paper to remove excess oil. Cook the rest of the pancakes.Serve warm with eg berry compote, jam and (optional though popular) sour cream.",
    category:"Desserts"
    },
    {
    name: "Kyiv Cake (Ukrainian Classic)",
    image: "/kievCake.png",
    description: "Kiyv Cake is light and airy in the center, with a bit of a crunch, sandwiched by soft sponge layers. It’s a true Ukrainian Classic cake. It takes an effort of love, but the outcome will have you come for seconds!",
    ingredients: ["1 sponge cake:", "5 large eggs", "3/4 cup sugar", "1 cup all purpose flour", "6 egg whites at room temperature","1 1/3 cup sugar", "1 cup hazelnuts chopped", "2 cup jam strawberry, peach or apricot", "CREAM:",  "6 egg yolks", "1/3 cup water", "8 tbsp condensed milk", "4 oz chocolate chips", "400 g Unsalted Butter room temperature"],
    directions:["SPONGE CAKE:", "Step -1", "Preheat oven to 350,", "Step - 2", "Beat 5 eggs (no need to separate them) on low speed and then on high speed for about 5 minutes or until it's three times in volume.", "Step -3", "Using a spatula, fold in flour by thirds be very gentle with the dough so you don’t over mix it and lose the fluffiness.", "Step - 4", "Add cake batter to an oiled baking sheet. Springform baking pan works amazing, size 9-12 inches is perfect.", "Step - 5", "Bake at 350F for 30 minutes and check it using a wooden toothpick. If the cake is ready, the dough should not stick to the toothpick. Prepare an 11 inch sponge cake.",  "MERINGUE:", "Step - 1", "Whip egg whites on high speed until they are doubled in volume." ,"Step - 2" , "Using a spatula, stir in a circular motion while gently mixing in the hazelnuts.", "Step - 3", "Spread the mixture onto 11 inch baking pan, lined with parchment paper or aluminum foil. Bake it at 250°F for 6 hours.", "CREAM:", "Step - 1", "In a small pot, beat egg yolks. Add water and condensed milk, and stir until smooth." , "Step - 2", "Cook all ingredients on very low heat. Continue mixing the cream the entire time to prevent the cream from sticking to corners. Slowly increase the heat, but do not bring the mixture to a boil. Cook until the mixture attains the texture of condensed milk, about 5-10 minutes.", "Step - 3", "Remove the mixture from the heat and add chocolate chips. Allow a few minutes for the mixture to melt, before mixing it through. Let the mixture cool off to room temperature.", "Step - 4", "In a separate bowl, beat butter. Once the butter is fluffy, add the cream mixture to the butter, a few spoonfuls at a time, until fully blended.", "FINALIZING:", "Using a serrated knife, slice the sponge cake horizontally in half. Cover each layer with jam, excluding the top layer.", "Place the first layer of sponge cake and cover it with cream, followed by meringue, then again, a layer of cream.Once the cake is put together, frost the sides, then top with the remaining cream and your choice of decoration."],
    category:"Desserts"
},
]

module.exports = recipe